### ISSUE TITLE
Error building executable: exit status 1

### ISSUE THREAD

**Issue by ZaddyWaddy** [EvilBytecode/ThunderKitty#18]
main.go:6:2: found packages HideConsole (hideconsole.go) and HideConsoleWindow (hideconsolewindow.go) in C:\Users\urfat\Desktop\ThunderKitty-main\utils\hideconsole
Error building executable: exit status 1

also gives this sometimes
#modernc.org/sqlite/lib
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\hooks.go:13:7: undefined: libc.X__ccgo_sqlite3_log
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:347:28: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:356:33: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:365:28: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:398:66: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:407:66: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:26349:12: undefined: libc.X__mingw_vsnwprintf
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92826:10: undefined: libc.X_InterlockedCompareExchange
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92832:9: undefined: libc.XInitializeCriticalSection
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92854:10: undefined: libc.X_InterlockedCompareExchange
..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92854:10: too many errors
main.go:6:2: found packages HideConsole (hideconsole.go) and HideConsoleWindow (hideconsolewindow.go) in C:\Users\urfat\Desktop\ThunderKitty-main\utils\hideconsole

**Comment by EvilBytecode** [comment]
My friend @SecDbg will look at it, since my english is corrupted💀

**Comment by ZaddyWaddy** [comment]
ah thanks for the help i was thinking it was to do with the version of mingw i had or something im on the latest one i thought i might have needed to downgrade tho

**Comment by ZaddyWaddy** [comment]
# modernc.org/sqlite/lib
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\hooks.go:13:7: undefined: libc.X__ccgo_sqlite3_log
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:347:28: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:356:33: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:365:28: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:398:66: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:407:66: tls.ID undefined (type *libc.TLS has no field or method ID)
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:26349:12: undefined: libc.X__mingw_vsnwprintf
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92826:10: undefined: libc.X_InterlockedCompareExchange
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92832:9: undefined: libc.XInitializeCriticalSection
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92854:10: undefined: libc.X_InterlockedCompareExchange
..\..\..\..\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\sqlite_windows.go:92854:10: too many errors
Error building executable: exit status 1


yeah i downloaded the latest one and it gives me that ill take more of a look into it

**Comment by EvilBytecode** [comment]
are you on windows?

**Comment by SecDbg** [comment]
The issue happens on Windows, both 10 and 11. I still can't reproduce it so not sure why.

**Comment by EvilBytecode** [comment]
i will reproduce with you

**Comment by ZaddyWaddy** [comment]
windows 11 yeah

**Comment by ZaddyWaddy** [comment]
im trying with msys64 apparently before i had some other one like cygwin or smth like that i forgot what it said

**Comment by SecDbg** [comment]
Cygwin is the same thing as Msys or whatever as far as I know, they're both just CLI tools.
Did you install MinGW-w64 using Msys like the Microsoft guide stated?

**Comment by ZaddyWaddy** [comment]
i did just now not before tho im trying it its taking a while for the go run command to work tho

**Comment by ZaddyWaddy** [comment]
yeah im so cooked might just install linux on a vm

**Comment by ZaddyWaddy** [comment]
![image](https://github.com/EvilBytecode/ThunderKitty/assets/96938274/e0e91401-b73b-44be-8217-a0ef2203fc55)

**Comment by SecDbg** [comment]
hmm so gcc is installed
also idk if the builder would work for linux, haven't tested compatibility
you get the error while trying to actually build the stub right? not when running the builder

**Comment by ZaddyWaddy** [comment]
yeah when building the stub
![image](https://github.com/EvilBytecode/ThunderKitty/assets/96938274/b725c3c5-f6f1-42f7-a009-5812b7622ef2)

**Comment by ZaddyWaddy** [comment]
![image](https://github.com/EvilBytecode/ThunderKitty/assets/96938274/b3156418-a744-4946-8143-5fdb6aa56c5f)
idk man

**Comment by SecDbg** [comment]
Damnit. One solution I might suggest is creating a Windows VM and installing the Go toolkit and MinGW-w64 through Mysy2.
You won't be able to use the actual builder gui, but you can copy the main.go file from your main pc and build it using the command `go build -ldflags "-s -w -H=windowsgui" main.go`

**Comment by SecDbg** [comment]
You have to copy over the other files aswell if you do that. Might work

**Comment by ZaddyWaddy** [comment]
any specific windows version or nah?

**Comment by ZaddyWaddy** [comment]
i might try win 10 cuz im on win 11 right now

**Comment by SecDbg** [comment]
Windows 11 worked for me, but windows 10 is compatible the same as far as i know

**Comment by SecDbg** [comment]
latest is fine, same with msys2 and mingw toolchain. latest versions of all

**Comment by SecDbg** [comment]
At this point I've no idea what actually causes the error. I doubt it's anything hardware related but at the same time I've had someone reinstall everything from scratch to no avail

**Comment by ZaddyWaddy** [comment]
is the visual studio code extension a requirement or nah

**Comment by SecDbg** [comment]
Nah vsc isn't required at all

**Comment by ZaddyWaddy** [comment]
alright the vm is installing right now

**Comment by ZaddyWaddy** [comment]
vm gave me an error about the graphics driver or something idk what happened

**Comment by ZaddyWaddy** [comment]
im trying to do it after uninstalling git on my pc now

**Comment by ZaddyWaddy** [comment]
yeah nah didnt work fuck knows

**Comment by EvilBytecode** [comment]
@SecDbg maybe we will release a console app? so we can avoid these typa problems?

**Comment by ZaddyWaddy** [comment]
okay i fixed it by changing all the sqlite ones u used to this one github.com/mattn/go-sqlite3

**Comment by ZaddyWaddy** [comment]
not sure if it will still send the stuff to telegram but i can see maybe?

**Comment by ZaddyWaddy** [comment]
it works

**Comment by SecDbg** [comment]
> @SecDbg maybe we will release a console app? so we can avoid these typa problems?

builder isn't the issue. stub is

**Comment by ZaddyWaddy** [comment]
yeah

**Comment by ZaddyWaddy** [comment]
![image](https://github.com/EvilBytecode/ThunderKitty/assets/96938274/ab0f2d16-8f1b-442b-afce-a425635f756f)

**Comment by ZaddyWaddy** [comment]
just from changing it over to the other sqlite github.com/mattn/go-sqlite3

**Comment by SecDbg** [comment]
did you change the code at all, for the different sqlite package, or did you keep it the same?

**Comment by ZaddyWaddy** [comment]
i changed the code in utils/browser for a few of them i think conn cookies downloads history logins all those just changing them to github.com/mattn/go-sqlite3 instead of the modernc

**Comment by ZaddyWaddy** [comment]
everything still seems to be working with it to such as anti triage vm 
![image](https://github.com/EvilBytecode/ThunderKitty/assets/96938274/45738a34-e225-4ae1-835d-8f53b7699c82)
and other stuff

**Comment by ZaddyWaddy** [comment]
should i upload it to virus total or another site?

**Comment by SecDbg** [comment]
it'll be detected right now anyway, stealer isn't undetected by windows defender atm as far as i know

**Comment by ZaddyWaddy** [comment]
alr alr

**Comment by SecDbg** [comment]
something is flagging, no idea if its a string or byte sequence or what

**Comment by SecDbg** [comment]
idk if we're gonna continue working on thunderkitty, i might start working on my own one that does everything in memory

**Comment by ZaddyWaddy** [comment]
still 6/74 on virus total thats crazy

**Comment by ZaddyWaddy** [comment]
not detected by malwarebytes either which is what most ppl use

**Comment by SecDbg** [comment]
it'll stay that way for a while, Go is a great language for avoiding detections because of how the compiler works

**Comment by SecDbg** [comment]
> not detected by malwarebytes either which is what most ppl use

most use windows defender unfortunately
also idk if it bypasses malwarebytes runtime, virustotal is scantime but doesnt show runtime

**Comment by ZaddyWaddy** [comment]
ah

**Comment by ZaddyWaddy** [comment]
it bypassed malware bytes scan on my pc 
![image](https://github.com/EvilBytecode/ThunderKitty/assets/96938274/83c75f3c-5f2d-4f5b-9869-49ed8ce3782f)

**Comment by SecDbg** [comment]
still scantime, try running it and see what happens, if it gets detected

**Comment by ZaddyWaddy** [comment]
yeah windows defender didnt pick it up either my  friend tested it too didnt get detected by either

**Comment by SecDbg** [comment]
didn't get detected when running? sick

**Comment by ZaddyWaddy** [comment]
yeah
