### ISSUE TITLE
installation error.

### ISSUE THREAD

**Issue by unoxyzmdfckz** [EvilBytecode/ThunderKitty#25]
![image](https://github.com/user-attachments/assets/a3899f91-ebd9-4f5c-9211-4eca8b8bd11c)

**Comment by SecDbg** [comment]
Fyne is a fucking mess, will eventually be fixed once someone is actually bothered to rewrite the program to have a CLI builder and not only a gui one. Possible fix, you can run the main.bat file or whatever it's called and see if that fixes
