### ISSUE TITLE
fyne

### ISSUE THREAD

**Issue by pr0niums** [EvilBytecode/ThunderKitty#27]
..\..\..\go\pkg\mod\github.com\srwiley\rasterx@v0.0.0-20220730225603-2ab79fcdd4ef\dash.go:8:2: missing go.sum entry for module providing package golang.org/x/image/math/fixed (imported by fyne.io/fyne/v2/widget); to add:
        go get fyne.io/fyne/v2/widget@v2.5.1
..\..\..\go\pkg\mod\github.com\srwiley\rasterx@v0.0.0-20220730225603-2ab79fcdd4ef\scan.go:19:2: missing go.sum entry for module providing package golang.org/x/image/vector (imported by github.com/srwiley/rasterx); to add:
        go get github.com/srwiley/rasterx@v0.0.0-20220730225603-2ab79fcdd4ef
..\..\..\go\pkg\mod\github.com\srwiley\oksvg@v0.0.0-20221011165216-be6e8873101c\public.go:21:2: missing go.sum entry for module providing package golang.org/x/image/colornames (imported by github.com/srwiley/oksvg); to add:
        go get github.com/srwiley/oksvg@v0.0.0-20221011165216-be6e8873101c
..\..\..\go\pkg\mod\github.com\srwiley\oksvg@v0.0.0-20221011165216-be6e8873101c\public.go:22:2: missing go.sum entry for module providing package golang.org/x/net/html/charset (imported by github.com/srwiley/oksvg); to add:
        go get github.com/srwiley/oksvg@v0.0.0-20221011165216-be6e8873101c
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\storage\repository\parse.go:9:2: missing go.sum entry for module providing package github.com/fredbi/uri (imported by fyne.io/fyne/v2/storage/repository); to add:
        go get fyne.io/fyne/v2/storage/repository@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\lang\lang.go:13:2: missing go.sum entry for module providing package github.com/jeandeaual/go-locale (imported by fyne.io/fyne/v2/lang); to add:
        go get fyne.io/fyne/v2/lang@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\lang\lang.go:14:2: missing go.sum entry for module providing package github.com/nicksnyder/go-i18n/v2/i18n (imported by fyne.io/fyne/v2/lang); to add:
        go get fyne.io/fyne/v2/lang@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\lang\lang.go:18:2: missing go.sum entry for module providing package golang.org/x/text/language (imported by fyne.io/fyne/v2/lang); to add:
        go get fyne.io/fyne/v2/lang@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\internal\painter\font.go:11:2: missing go.sum entry for module providing package github.com/go-text/render (imported by fyne.io/fyne/v2/internal/painter); to add:
        go get fyne.io/fyne/v2/internal/painter@v2.5.1
..\..\..\go\pkg\mod\github.com\go-text\typesetting@v0.1.0\opentype\api\font\glyphs.go:16:2: missing go.sum entry for module providing package golang.org/x/image/tiff (imported by github.com/go-text/typesetting/opentype/api/font); to add:
        go get github.com/go-text/typesetting/opentype/api/font@v0.1.0
..\..\..\go\pkg\mod\github.com\go-text\typesetting@v0.1.0\shaping\input.go:15:2: missing go.sum entry for module providing package golang.org/x/text/unicode/bidi (imported by github.com/go-text/typesetting/shaping); to add:
        go get github.com/go-text/typesetting/shaping@v0.1.0
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\internal\painter\image.go:8:2: missing go.sum entry for module providing package golang.org/x/image/draw (imported by fyne.io/fyne/v2/internal/painter); to add:
        go get fyne.io/fyne/v2/internal/painter@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\widget\markdown.go:8:2: missing go.sum entry for module providing package github.com/yuin/goldmark (imported by fyne.io/fyne/v2/widget); to add:
        go get fyne.io/fyne/v2/widget@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\widget\markdown.go:9:2: missing go.sum entry for module providing package github.com/yuin/goldmark/ast (imported by fyne.io/fyne/v2/widget); to add:
        go get fyne.io/fyne/v2/widget@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\widget\markdown.go:10:2: missing go.sum entry for module providing package github.com/yuin/goldmark/renderer (imported by fyne.io/fyne/v2/widget); to add:
        go get fyne.io/fyne/v2/widget@v2.5.1
package command-line-arguments
        imports fyne.io/fyne/v2/app
        imports fyne.io/fyne/v2/internal/driver/glfw
        imports fyne.io/fyne/v2/internal/driver/common
        imports fyne.io/fyne/v2/internal/painter/gl
        imports github.com/go-gl/gl/v2.1/gl: build constraints exclude all Go files in C:\Users\seven\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20211210172815-726fda9656d6\v2.1\gl
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\internal\driver\glfw\driver_desktop.go:19:2: missing go.sum entry for module providing package fyne.io/systray (imported by fyne.io/fyne/v2/internal/driver/glfw); to add:
        go get fyne.io/fyne/v2/internal/driver/glfw@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\internal\driver\glfw\clipboard.go:11:2: missing go.sum entry for module providing package github.com/go-gl/glfw/v3.3/glfw (imported by fyne.io/fyne/v2/internal/driver/glfw); to add:
        go get fyne.io/fyne/v2/internal/driver/glfw@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\internal\metadata\load.go:8:2: missing go.sum entry for module providing package github.com/BurntSushi/toml (imported by fyne.io/fyne/v2/internal/metadata); to add:
        go get fyne.io/fyne/v2/internal/metadata@v2.5.1
..\..\..\go\pkg\mod\fyne.io\fyne\v2@v2.5.1\app\settings_desktop.go:10:2: missing go.sum entry for module providing package github.com/fsnotify/fsnotify (imported by fyne.io/fyne/v2/app); to add:
        go get fyne.io/fyne/v2/app@v2.5.1
        
        why

**Comment by bensgaming** [comment]
same

**Comment by PhantomPeek** [comment]
Easy fix, make sure GIT is installed then run these commands in same dir as the project 
go get fyne.io/fyne/v2/widget@v2.5.1
go get github.com/srwiley/rasterx@v0.0.0-20220730225603-2ab79fcdd4ef
go get github.com/srwiley/oksvg@v0.0.0-20221011165216-be6e8873101c
go get fyne.io/fyne/v2/lang@v2.5.1
go get github.com/go-text/render@v0.1.1-0.20240418202334-dd62631dae9b
go get fyne.io/fyne/v2/internal/painter@v2.5.1
go get fyne.io/fyne/v2/internal/metadata@v2.5.1

**Comment by EvilBytecode** [comment]
NEW VERSION RELEASED - OUTDATED. FYNE NO LONGER USED - EASY TO USE - WORKS ON VMS
