### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by pr0niums** [EvilBytecode/ThunderKitty#30]
C:\Users\seven\Desktop\ThunderKitty-main>go run main_gui.go
package command-line-arguments
        imports fyne.io/fyne/v2/app
        imports fyne.io/fyne/v2/internal/driver/glfw
        imports fyne.io/fyne/v2/internal/driver/common
        imports fyne.io/fyne/v2/internal/painter/gl
        imports github.com/go-gl/gl/v2.1/gl: build constraints exclude all Go files in C:\Users\seven\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20211210172815-726fda9656d6\v2.1\gl

**Comment by SecDbg** [comment]
Yeah fyne is buggy as fuck, don't bother using this stealer, it's broken as fuck anyway
